server:
  port: 9091
db:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: ""
  database: "cflion"
  maxIdle: 20
  maxOpen: 100
logging:
  level: DEBUG
etcd:
  formal:
    - "127.0.0.1:2379"
  dev:
    - "127.0.0.1:2379"
